### ISSUE TITLE
洗脑与爱国主义教育 | 无二自留地

### ISSUE THREAD

**Issue by yeahwu** [yeahwu/yeahwu.github.io#24]
https://www.12ab.cf/posts/c7607ee2.html#more 

 文 | 杨恒均 　　苏联著名的科学家巴甫洛夫发现了“条件反射”：当他在训练一条狗时，把食物与某种动作联系起来，那么今后他指令这条狗做某种动作就非常容易，甚至狗会为了食物而不自觉地做某个动作。列宁听说了巴甫洛夫的理论，若有所思，过了几天，他让人把巴甫洛夫招进宫来。

**Comment by t-k-** [comment]
我觉得现在连国这个概念都应该思考一下（你说痛恨洗脑其实是因为爱国），一个人只想跟思想和目标相近，价值观相近的人在一起，这并不意味着他或她非要诞生在一样的国度。虽然受一样的文化熏陶更可能有相似的价值观，但我爱的是一个我想爱的集体，每个人爱的集体都可以不一样，而爱国主义就是在混淆这个便捷为掌权者服务而已。每个人做出爱哪个集体都是他的选择，我就是希望找到不但我喜欢，而且这个集体也能帮助我的，无论职业、出身、语言、宗教。所以希望你不是爱国而去痛恨洗脑，而更应该考虑是不是我 care 的人被洗脑了。我自己的经验里，和我有相似思想和价值观的朋友，很少有被洗脑的，所以我不会因为那些和我无关的人被洗脑而难过。
