### ISSUE TITLE
村上春树演讲：高墙与鸡蛋 | 无二自留地

### ISSUE THREAD

**Issue by yeahwu** [yeahwu/yeahwu.github.io#31]
https://www.12ab.cf/posts/805d27fd.html#more 

 “假如这里有坚固的高墙和撞墙破碎的鸡蛋，我总是站在鸡蛋一边。—— 村上春树” 我作为一个小说家，换句话说，作为以巧妙说谎为职业的人来到这里、来到耶路撒冷市。 当然，说谎的不都是小说家。诸位知道，政治家屡屡说谎，外交官和军人说谎，二手车推销员和肉铺和建筑业者也说谎。但小说家说谎和他们说谎的不同之处在于：小说家说谎不受道义上的谴责。莫如说谎说得越大越高明，小说家越能得到人们的赞赏和好评。为什么呢？

**Comment by t-k-** [comment]
看见这句话了吗“我们都是超越国籍、种族和宗教的一个一个的人”。你这么有良知的人，不要再为这么大人口的国家操劳伤害自己了，改变一个人都不可能（他大脑里的神经元结构除非外科手术否则很可能很难改变，毕竟他的前半生的环境和生母决定了大部分结构）。找到自己的集体，去努力用脚走到自己向往的地方，关心和帮助自己爱的集体。

**Comment by yeahwu** [comment]
@t-k-  俺传这些文章，并没有妄想改变一些人。只是想让年轻人看到后能有一些怀疑，一些愤怒，或者不屑一顾，更有甚者想破口大骂“尔等蛊惑”，只要让他们感受到不同，俺也就知足了！
至于你说的少为国操心，呵呵，那么留给下一代一个现在的香港？
网站域名变更，评论链接也变更了，所以直接在github里面留言。新域名：
https://www.yeahwu.com/

**Comment by t-k-** [comment]
如果你的后代喜欢一个地区，他可以过去工作。如果他不喜欢，他可以走开。我些话恰恰只希望改变你而已。
